# Generated by Django 4.1 on 2022-08-31 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0001_initial'),
        ('questions', '0001_initial'),
        ('countries', '0001_initial'),
        ('answers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='best_answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_for_question', to='answers.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(on_delete=models.SET('en'), to='languages.language'),
        ),
    ]
