# Generated by Django 4.1 on 2022-09-14 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.generic_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('original_text', models.TextField(verbose_name='Original text')),
                ('en_text', models.TextField(verbose_name='Translated to english text')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('-created',),
            },
            bases=(models.Model, utils.generic_fields.WithSelfContentTypeMixin),
        ),
        migrations.CreateModel(
            name='AnswerView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answer')),
            ],
            options={
                'verbose_name': 'Answer view',
                'verbose_name_plural': 'Answer views',
                'ordering': ('-answer__created',),
            },
        ),
    ]
