# Generated by Django 4.1 on 2022-08-15 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('score', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1, verbose_name='Like/dislike')),
                ('liked_object_id', models.IntegerField(verbose_name='Liked/disliked question/answer id')),
                ('liked_object_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'answers'), ('model', 'answer')), models.Q(('app_label', 'questions'), ('model', 'question')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ('-created',),
            },
        ),
    ]
