# Generated by Django 4.1 on 2022-08-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_object_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'answers'), ('model', 'answer')), models.Q(('app_label', 'questions'), ('model', 'question')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
